\newlabel{chap:abstract_de}
\newlabel{chap:abstract}
\newlabel{chap:ack}
\newlabel{chap:algorithm}
\newlabel{chap:appendix}
\newlabel{chap:backgroundandrelatedwork}
\newlabel{chap:conclusion}
\newlabel{chap:implementation}
\newlabel{chap:introduction}
\newlabel{chap:prepublished_papers}
\newlabel{eqn:bmpre}
\newlabel{eqn:censustransform}
\newlabel{eqn:dm}
\newlabel{eqn:shd}
\newlabel{fig:algorithmstructure}
\newlabel{fig:algorithm}
\newlabel{fig:algort}
\newlabel{fig:algover}
\newlabel{fig:assumptionssv}
\newlabel{fig:bmpre1}
\newlabel{fig:bmpre2}
\newlabel{fig:bmpre}
\newlabel{fig:bsv}
\newlabel{fig:censusexample}
\newlabel{fig:cpugpu}
\newlabel{fig:diffpixegpu}
\newlabel{fig:dmappartsu}
\newlabel{fig:dmcone}
\newlabel{fig:dsoptimization}
\newlabel{fig:gpuegpu}
\newlabel{fig:icmoptimization}
\newlabel{fig:kernelstruct}
\newlabel{fig:morphologicaldilation}
\newlabel{fig:morphologicalerosion}
\newlabel{fig:negation}
\newlabel{fig:nemaarch}
\newlabel{fig:parsumoptimization}
\newlabel{fig:rastint}
\newlabel{fig:reflection}
\newlabel{fig:samplessv}
\newlabel{fig:sfig1}
\newlabel{fig:sfig1}
\newlabel{fig:sfig1}
\newlabel{fig:sfig1}
\newlabel{fig:sfig1}
\newlabel{fig:sfig2}
\newlabel{fig:sfig2}
\newlabel{fig:sfig2}
\newlabel{fig:sfig2}
\newlabel{fig:sfig2}
\newlabel{fig:sfig3}
\newlabel{fig:sfig3}
\newlabel{fig:sfig4}
\newlabel{fig:sfig4}
\newlabel{fig:sfig5}
\newlabel{fig:sfig5}
\newlabel{fig:sfig6}
\newlabel{fig:sfig6}
\newlabel{fig:sfig7}
\newlabel{fig:sfig8}
\newlabel{fig:sfrl}
\newlabel{fig:sfrr}
\newlabel{fig:shdalgorithm}
\newlabel{fig:xoroptimization}
\newlabel{s:algorithm:dmcalculation}
\newlabel{s:algorithm:preprocessing}
\newlabel{s:algorithm}
\newlabel{s:fverificationres:mw}
\newlabel{s:fverificationres:mw}
\newlabel{s:fverificationres:shdw}
\newlabel{s:gpuhw:nema}
\newlabel{s:gpuhw}
\newlabel{s:gpusw:nema}
\newlabel{s:gpusw:nkernels}
\newlabel{s:gpusw}
\newlabel{s:hostero}
\newlabel{s:kerero}
\newlabel{s:optimizations:dsoptimization}
\newlabel{s:optimizations:invariantcodemotion}
\newlabel{s:optimizations:multithreading}
\newlabel{s:optimizations:shdoptimization}
\newlabel{s:optimizations:simd}
\newlabel{s:optimizations:xoroptimization}
\newlabel{s:requirements}
\newlabel{s:rwork:summary}
\newlabel{s:rwork}
\newlabel{s:stereovision:bmpre}
\newlabel{s:stereovision}
\newlabel{sec:aresults}
\newlabel{sec:fperformance}
\newlabel{sec:fverificationres}
\newlabel{sec:intro:contrib}
\newlabel{sec:intro:outline}
\newlabel{sec:intro:probstatement}
\newlabel{sec:kernelchoice}
\newlabel{sec:optdmalgo}
\newlabel{sec:optimizations}
\newlabel{sec:parameters}
\newlabel{sec:rtperformance}
\newlabel{sec:summary3}
\newlabel{sub@fig:sfig1}
\newlabel{sub@fig:sfig1}
\newlabel{sub@fig:sfig1}
\newlabel{sub@fig:sfig1}
\newlabel{sub@fig:sfig1}
\newlabel{sub@fig:sfig2}
\newlabel{sub@fig:sfig2}
\newlabel{sub@fig:sfig2}
\newlabel{sub@fig:sfig2}
\newlabel{sub@fig:sfig2}
\newlabel{sub@fig:sfig3}
\newlabel{sub@fig:sfig3}
\newlabel{sub@fig:sfig4}
\newlabel{sub@fig:sfig4}
\newlabel{sub@fig:sfig5}
\newlabel{sub@fig:sfig5}
\newlabel{sub@fig:sfig6}
\newlabel{sub@fig:sfig6}
\newlabel{sub@fig:sfig7}
\newlabel{sub@fig:sfig8}
\newlabel{sub@fig:sfrl}
\newlabel{sub@fig:sfrr}
\newlabel{tab:bmprenema}
\newlabel{tab:bmpre}
\newlabel{tab:hwplat}
\newlabel{tab:nemartneg}
\newlabel{tab:nemart}
